language: node_js
node_js:
  - node
  - lts/*
  - '8'
after_success:
  - nyc report --reporter=text-lcov | npx coveralls
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
